# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0013_auto_20160618_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionMonitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_timeDay', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_timeDay', models.DateTimeField(null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccionmonitoria_estudiante', to=settings.AUTH_USER_MODEL)),
                ('reunionsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.ReunionSite')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccionmonitoria_tutor', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.University')),
            ],
        ),
    ]
