# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0002_seccionmonitoria_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionmonitoria',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
