# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0003_seccionmonitoria_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionmonitoria',
            name='status',
            field=models.CharField(choices=[('aceptado', 'Aceptada'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
