# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0005_auto_20160625_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionmonitoria',
            name='hours_wanted',
            field=models.IntegerField(default='2'),
        ),
    ]
