# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0006_seccionmonitoria_hours_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionmonitoria',
            name='payment_method',
            field=models.CharField(choices=[('online', 'online'), ('efectivo', 'efectivo')], default='online', max_length=10),
        ),
    ]
