# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import monitorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0009_affiliatecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='reunion_site_directory/no-image.jpg', upload_to=monitorias.models.affiliate_company_directory)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
