# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0010_recommendedtools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedtools',
            options={'verbose_name_plural': 'recommendedTools'},
        ),
    ]
