# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0011_auto_20160702_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedtools',
            options={'verbose_name_plural': 'recommended Tools'},
        ),
    ]
