# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import monitorias.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0012_auto_20160702_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedtools',
            name='picture',
            field=models.ImageField(default='reunion_site_directory/no-image.jpg', upload_to=monitorias.models.recommended_tools_directory),
        ),
    ]
