# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0014_publicity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicity',
            options={'verbose_name_plural': 'publicity Campaigns'},
        ),
    ]
