# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorias', '0015_auto_20160702_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecompany',
            name='google_maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliatecompany',
            name='laboring_days',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliatecompany',
            name='laboring_hours',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliatecompany',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='affiliatecompany',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
