# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_userprofile_istutor'),
        ('quickfireQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.Subject'),
        ),
    ]
