# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfireQuestions', '0002_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Subject'),
        ),
    ]
