# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfireQuestions', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isAnswered',
            field=models.BooleanField(default=False),
        ),
    ]
