# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.Area'),
        ),
        migrations.AlterField(
            model_name='university',
            name='reunion_sites',
            field=models.ManyToManyField(default='', to='user_profile.ReunionSite'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='career',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.Career'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(default='', to='user_profile.Subject'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.University'),
        ),
    ]
