# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='career',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career',
            field=models.ManyToManyField(to='user_profile.Career'),
        ),
    ]
