# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20160617_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='begin_time',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='end_time',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
