# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20160617_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='begin_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2016, 6, 17, 6, 4, 48, 869596, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2016, 6, 17, 6, 4, 48, 869596, tzinfo=utc)),
        ),
    ]
