# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20160617_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='begin_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='end_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
