# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20160617_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Career'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(null=True, to='user_profile.Subject'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.University'),
        ),
    ]
