# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20160617_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='user-character.png', upload_to=user_profile.models.user_directory_path),
        ),
    ]
