# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20160617_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(to='user_profile.Subject'),
        ),
    ]
