# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20160618_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isTutor',
            field=models.BooleanField(default=False),
        ),
    ]
