# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_userprofile_istutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quickfirequestions_available',
            field=models.IntegerField(default=0),
        ),
    ]
