# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_auto_20160702_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='begin_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='end_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
